server:
  port: 8080

spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
  application:
    version: 0.0.1
    name: x-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: localhost:9000/oauth2/jwks
  grpc:
    client:
      product-service:
        address: static://product-service:9090
        negotiation-type: plaintext
      user-service:
        address: static://user-service:9090
        negotiation-type: plaintext
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  prometheus:
    metrics:
      export:
        enabled: true
security:
  jwt:
    # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
    secret: ${SECURITY_AUTHENTICATION_JWT_SECRET:OGEzMWZkOTQzYTI3ZjMwNTJmNTEwYjUwZjMxN2ZiOTljODgyODhkNTkwMzllYWIyYjVhOTMzNzZkYzM4MzI0NDFmMzJhNmQwZTExNjU3ZTBkZmNmZTY2MzlkYjVlZmNlMjI0M2Y3MWUzN2YwMjczYTU4YmFjZGU0M2MzNzZiNDc=}
    # Token is valid 24 hours
    token-validity-in-seconds: ${JWT_TOKEN_VALIDITY_IN_SECONDS:86400}
    token-validity-in-seconds-for-remember-me: 2592000
  permit-all:
    - /api/v1/user/register
    - /api/v1/user/login
    - /actuator
    - /graphiql
    - /user-graphql
  cross-origin:
    - "*"
  credentials: false
  allowed-headers:
    - Content-Type
    - Authorization
  allowed-methods:
    - POST
    - GET
    - PUT
    - DELETE
    - OPTIONS